// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package login

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"context"
	"fmt"
	"html"
	"io"
	"strings"

	"katchup/internal/view/layout"

	"github.com/a-h/templ"
)

// PageData drives the login / first-run setup page.
type PageData struct {
	// Setup is true when no access key exists yet: the page asks the user to
	// create one instead of asking for the existing one.
	Setup bool
	Error string
}

const inputCls = "w-full rounded-xl border border-white/10 bg-ink-950/80 px-3.5 py-2.5 text-sm text-zinc-100 placeholder:text-mute/60 outline-none transition focus:border-ketchup/60 focus:ring-2 focus:ring-ketchup/25"

// LoginPage renders the standalone (nav-less) login or first-run setup card.
func LoginPage(data PageData) templ.Component {
	inner := templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		var b strings.Builder

		b.WriteString(`<div class="rise w-full max-w-sm">`)
		b.WriteString(`<div class="mb-6 flex items-center justify-center gap-2.5">
			<span class="grid h-10 w-10 place-items-center rounded-xl bg-ketchup/15 text-xl ring-1 ring-inset ring-ketchup/30">🥫</span>
			<span class="font-display text-2xl font-bold lowercase tracking-tight text-white">katchup</span>
		</div>`)

		b.WriteString(`<div class="rounded-2xl border border-white/10 bg-ink-900/60 p-6 shadow-2xl shadow-black/40">`)
		if data.Setup {
			b.WriteString(`<h1 class="font-display text-lg font-semibold text-white">Create an access key</h1>
			<p class="mt-1.5 text-sm text-mute">No access key is configured. Choose one now — it will be required to open this UI. To prove you run this server, enter the one-time setup token printed in its log (<span class="font-mono text-[12px]">docker compose logs katchup | grep setup_token</span>). (You can also set <span class="font-mono text-[12px]">KATCHUP_UI_KEY</span> in the environment instead.)</p>`)
		} else {
			b.WriteString(`<h1 class="font-display text-lg font-semibold text-white">Unlock</h1>
			<p class="mt-1.5 text-sm text-mute">Enter the access key for this archive.</p>`)
		}

		if data.Error != "" {
			fmt.Fprintf(&b, `<div class="mt-4 rounded-xl border border-ketchup/40 bg-ketchup/10 px-3.5 py-2.5 text-sm text-ketchup">%s</div>`, html.EscapeString(data.Error))
		}

		b.WriteString(`<form method="POST" action="/login" class="mt-5 space-y-4">`)
		if data.Setup {
			b.WriteString(`<input type="hidden" name="mode" value="setup">`)
			fmt.Fprintf(&b, `<div>
				<label class="mb-1.5 block font-mono text-[11px] uppercase tracking-widest text-mute">Setup token (from the server log)</label>
				<input type="text" name="token" required autofocus autocomplete="off" spellcheck="false" class="%s font-mono">
			</div>
			<div>
				<label class="mb-1.5 block font-mono text-[11px] uppercase tracking-widest text-mute">Access key</label>
				<input type="password" name="key" required minlength="8" autocomplete="new-password" class="%s">
			</div>
			<div>
				<label class="mb-1.5 block font-mono text-[11px] uppercase tracking-widest text-mute">Confirm key</label>
				<input type="password" name="confirm" required minlength="8" autocomplete="new-password" class="%s">
			</div>`, inputCls, inputCls, inputCls)
			b.WriteString(`<button type="submit" class="w-full rounded-xl bg-ketchup px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ketchup-600">Create key &amp; unlock</button>`)
		} else {
			fmt.Fprintf(&b, `<div>
				<label class="mb-1.5 block font-mono text-[11px] uppercase tracking-widest text-mute">Access key</label>
				<input type="password" name="key" required autofocus autocomplete="current-password" class="%s">
			</div>`, inputCls)
			b.WriteString(`<button type="submit" class="w-full rounded-xl bg-ketchup px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ketchup-600">Unlock</button>`)
		}
		b.WriteString(`</form></div></div>`)

		_, err := io.WriteString(w, b.String())
		return err
	})

	title := "Unlock"
	if data.Setup {
		title = "Set up"
	}
	return layout.Bare(title, inner)
}
