// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package database

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, host, port, username, encrypted_password, use_ssl, folders)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, name, host, port, username, encrypted_password, use_ssl, folders, created_at, updated_at
`

type CreateAccountParams struct {
	Name              string `json:"name"`
	Host              string `json:"host"`
	Port              int64  `json:"port"`
	Username          string `json:"username"`
	EncryptedPassword string `json:"encrypted_password"`
	UseSsl            int64  `json:"use_ssl"`
	Folders           string `json:"folders"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.EncryptedPassword,
		arg.UseSsl,
		arg.Folders,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.EncryptedPassword,
		&i.UseSsl,
		&i.Folders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, host, port, username, encrypted_password, use_ssl, folders, created_at, updated_at
FROM accounts
WHERE id = ?1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.EncryptedPassword,
		&i.UseSsl,
		&i.Folders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, host, port, username, encrypted_password, use_ssl, folders, created_at, updated_at,
    (SELECT COUNT(*) FROM sync_runs WHERE account_id = accounts.id AND status = 'running')
    AS is_syncing
FROM accounts
ORDER BY name ASC
`

type ListAccountsRow struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	Host              string `json:"host"`
	Port              int64  `json:"port"`
	Username          string `json:"username"`
	EncryptedPassword string `json:"encrypted_password"`
	UseSsl            int64  `json:"use_ssl"`
	Folders           string `json:"folders"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
	IsSyncing         int64  `json:"is_syncing"`
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.EncryptedPassword,
			&i.UseSsl,
			&i.Folders,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsSyncing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET
    name = ?1,
    host = ?2,
    port = ?3,
    username = ?4,
    encrypted_password = ?5,
    use_ssl = ?6,
    folders = ?7,
    updated_at = datetime('now')
WHERE id = ?8
RETURNING id, name, host, port, username, encrypted_password, use_ssl, folders, created_at, updated_at
`

type UpdateAccountParams struct {
	Name              string `json:"name"`
	Host              string `json:"host"`
	Port              int64  `json:"port"`
	Username          string `json:"username"`
	EncryptedPassword string `json:"encrypted_password"`
	UseSsl            int64  `json:"use_ssl"`
	Folders           string `json:"folders"`
	ID                int64  `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.EncryptedPassword,
		arg.UseSsl,
		arg.Folders,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.EncryptedPassword,
		&i.UseSsl,
		&i.Folders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
