// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encryption.sql

package database

import (
	"context"
	"database/sql"
)

const deleteAccountEncryption = `-- name: DeleteAccountEncryption :exec
DELETE FROM account_encryption WHERE account_id = ?1
`

func (q *Queries) DeleteAccountEncryption(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccountEncryption, accountID)
	return err
}

const getAccountEncryption = `-- name: GetAccountEncryption :one
SELECT id, account_id, yubikey_slot_id, slot_fingerprint, encrypted_content_key_prefix, created_at
FROM account_encryption
WHERE account_id = ?1
`

func (q *Queries) GetAccountEncryption(ctx context.Context, accountID int64) (AccountEncryption, error) {
	row := q.db.QueryRowContext(ctx, getAccountEncryption, accountID)
	var i AccountEncryption
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.YubikeySlotID,
		&i.SlotFingerprint,
		&i.EncryptedContentKeyPrefix,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountEncryptionByPrefix = `-- name: GetAccountEncryptionByPrefix :one
SELECT id, account_id, yubikey_slot_id, slot_fingerprint, encrypted_content_key_prefix, created_at
FROM account_encryption
WHERE account_id = ?1 AND encrypted_content_key_prefix = ?2
`

type GetAccountEncryptionByPrefixParams struct {
	AccountID                 int64          `json:"account_id"`
	EncryptedContentKeyPrefix sql.NullString `json:"encrypted_content_key_prefix"`
}

func (q *Queries) GetAccountEncryptionByPrefix(ctx context.Context, arg GetAccountEncryptionByPrefixParams) (AccountEncryption, error) {
	row := q.db.QueryRowContext(ctx, getAccountEncryptionByPrefix, arg.AccountID, arg.EncryptedContentKeyPrefix)
	var i AccountEncryption
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.YubikeySlotID,
		&i.SlotFingerprint,
		&i.EncryptedContentKeyPrefix,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountEncryption = `-- name: ListAccountEncryption :many
SELECT id, account_id, yubikey_slot_id, slot_fingerprint, encrypted_content_key_prefix, created_at
FROM account_encryption
ORDER BY account_id ASC
`

func (q *Queries) ListAccountEncryption(ctx context.Context) ([]AccountEncryption, error) {
	rows, err := q.db.QueryContext(ctx, listAccountEncryption)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountEncryption{}
	for rows.Next() {
		var i AccountEncryption
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.YubikeySlotID,
			&i.SlotFingerprint,
			&i.EncryptedContentKeyPrefix,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountEncryption = `-- name: UpsertAccountEncryption :one
INSERT INTO account_encryption (account_id, yubikey_slot_id, slot_fingerprint, encrypted_content_key_prefix)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(account_id) DO UPDATE SET
    yubikey_slot_id = excluded.yubikey_slot_id,
    slot_fingerprint = excluded.slot_fingerprint,
    encrypted_content_key_prefix = excluded.encrypted_content_key_prefix,
    created_at = datetime('now')
RETURNING id, account_id, yubikey_slot_id, slot_fingerprint, encrypted_content_key_prefix, created_at
`

type UpsertAccountEncryptionParams struct {
	AccountID                 int64          `json:"account_id"`
	YubikeySlotID             string         `json:"yubikey_slot_id"`
	SlotFingerprint           string         `json:"slot_fingerprint"`
	EncryptedContentKeyPrefix sql.NullString `json:"encrypted_content_key_prefix"`
}

func (q *Queries) UpsertAccountEncryption(ctx context.Context, arg UpsertAccountEncryptionParams) (AccountEncryption, error) {
	row := q.db.QueryRowContext(ctx, upsertAccountEncryption,
		arg.AccountID,
		arg.YubikeySlotID,
		arg.SlotFingerprint,
		arg.EncryptedContentKeyPrefix,
	)
	var i AccountEncryption
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.YubikeySlotID,
		&i.SlotFingerprint,
		&i.EncryptedContentKeyPrefix,
		&i.CreatedAt,
	)
	return i, err
}
