// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failed_uid.sql

package database

import (
	"context"
)

const clearFailedUID = `-- name: ClearFailedUID :exec
DELETE FROM failed_uids
WHERE account_id = ?1 AND folder = ?2 AND uidvalidity = ?3 AND uid = ?4
`

type ClearFailedUIDParams struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	Uidvalidity int64  `json:"uidvalidity"`
	Uid         int64  `json:"uid"`
}

func (q *Queries) ClearFailedUID(ctx context.Context, arg ClearFailedUIDParams) error {
	_, err := q.db.ExecContext(ctx, clearFailedUID,
		arg.AccountID,
		arg.Folder,
		arg.Uidvalidity,
		arg.Uid,
	)
	return err
}

const clearStaleFailedUIDs = `-- name: ClearStaleFailedUIDs :exec
DELETE FROM failed_uids
WHERE account_id = ?1 AND folder = ?2 AND uidvalidity <> ?3
`

type ClearStaleFailedUIDsParams struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	Uidvalidity int64  `json:"uidvalidity"`
}

// Drop failure records from other UIDVALIDITY generations of a folder; their
// UIDs no longer name anything on the server.
func (q *Queries) ClearStaleFailedUIDs(ctx context.Context, arg ClearStaleFailedUIDsParams) error {
	_, err := q.db.ExecContext(ctx, clearStaleFailedUIDs, arg.AccountID, arg.Folder, arg.Uidvalidity)
	return err
}

const listFailedUIDs = `-- name: ListFailedUIDs :many
SELECT uid, attempts FROM failed_uids
WHERE account_id = ?1 AND folder = ?2 AND uidvalidity = ?3
`

type ListFailedUIDsParams struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	Uidvalidity int64  `json:"uidvalidity"`
}

type ListFailedUIDsRow struct {
	Uid      int64 `json:"uid"`
	Attempts int64 `json:"attempts"`
}

func (q *Queries) ListFailedUIDs(ctx context.Context, arg ListFailedUIDsParams) ([]ListFailedUIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailedUIDs, arg.AccountID, arg.Folder, arg.Uidvalidity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailedUIDsRow{}
	for rows.Next() {
		var i ListFailedUIDsRow
		if err := rows.Scan(&i.Uid, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFailedUID = `-- name: RecordFailedUID :one
INSERT INTO failed_uids (account_id, folder, uidvalidity, uid, last_error)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(account_id, folder, uidvalidity, uid) DO UPDATE SET
    attempts = attempts + 1,
    last_error = excluded.last_error,
    updated_at = datetime('now')
RETURNING attempts
`

type RecordFailedUIDParams struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	Uidvalidity int64  `json:"uidvalidity"`
	Uid         int64  `json:"uid"`
	LastError   string `json:"last_error"`
}

// Count one more failed attempt for a message; returns the new total.
func (q *Queries) RecordFailedUID(ctx context.Context, arg RecordFailedUIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordFailedUID,
		arg.AccountID,
		arg.Folder,
		arg.Uidvalidity,
		arg.Uid,
		arg.LastError,
	)
	var attempts int64
	err := row.Scan(&attempts)
	return attempts, err
}
