// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package database

import (
	"context"
	"database/sql"
)

const adoptUIDValidity = `-- name: AdoptUIDValidity :exec
UPDATE OR IGNORE messages SET uidvalidity = ?1
WHERE account_id = ?2 AND folder = ?3 AND uidvalidity = 0
`

type AdoptUIDValidityParams struct {
	Uidvalidity int64  `json:"uidvalidity"`
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
}

// Stamp a folder's pre-UIDVALIDITY-tracking rows (uidvalidity = 0) with the
// server's current value the first time it is seen, so they keep matching
// ExistsMessage. OR IGNORE skips a row that would collide with one already
// recorded under that generation.
func (q *Queries) AdoptUIDValidity(ctx context.Context, arg AdoptUIDValidityParams) error {
	_, err := q.db.ExecContext(ctx, adoptUIDValidity, arg.Uidvalidity, arg.AccountID, arg.Folder)
	return err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM messages m
WHERE (?1 = 0 OR m.account_id = ?1)
  AND (?2 = '' OR substr(m.internal_date, 1, 10) = ?2)
  AND (?3 = '' OR m.internal_date >= ?3)
  AND (?4 = '' OR (m.internal_date <> '' AND m.internal_date < ?4))
`

type CountMessagesParams struct {
	AccountID interface{} `json:"account_id"`
	Date      interface{} `json:"date"`
	Since     interface{} `json:"since"`
	Before    interface{} `json:"before"`
}

func (q *Queries) CountMessages(ctx context.Context, arg CountMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages,
		arg.AccountID,
		arg.Date,
		arg.Since,
		arg.Before,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesByAccount = `-- name: CountMessagesByAccount :one
SELECT COUNT(*) FROM messages WHERE account_id = ?1
`

func (q *Queries) CountMessagesByAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsMessage = `-- name: ExistsMessage :one
SELECT COUNT(*) FROM messages
WHERE account_id = ?1 AND folder = ?2 AND uidvalidity = ?3 AND uid = ?4
`

type ExistsMessageParams struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	Uidvalidity int64  `json:"uidvalidity"`
	Uid         int64  `json:"uid"`
}

func (q *Queries) ExistsMessage(ctx context.Context, arg ExistsMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsMessage,
		arg.AccountID,
		arg.Folder,
		arg.Uidvalidity,
		arg.Uid,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArchivedByFuzzyFp = `-- name: GetArchivedByFuzzyFp :one
SELECT m.id, m.created_at, b.sha256 AS blob_sha256
FROM messages m
JOIN blobs b ON b.id = m.blob_id
WHERE m.fuzzy_fp = ?1
ORDER BY m.id DESC
LIMIT 1
`

type GetArchivedByFuzzyFpRow struct {
	ID         int64  `json:"id"`
	CreatedAt  string `json:"created_at"`
	BlobSha256 string `json:"blob_sha256"`
}

// Fuzzy fallback for archived-lookup when a Message-ID match misses: match on
// the fuzzy fingerprint (sha256 of normalized from|date|subject).
func (q *Queries) GetArchivedByFuzzyFp(ctx context.Context, fuzzyFp sql.NullString) (GetArchivedByFuzzyFpRow, error) {
	row := q.db.QueryRowContext(ctx, getArchivedByFuzzyFp, fuzzyFp)
	var i GetArchivedByFuzzyFpRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.BlobSha256)
	return i, err
}

const getArchivedByMessageID = `-- name: GetArchivedByMessageID :one
SELECT m.id, m.created_at, b.sha256 AS blob_sha256
FROM messages m
JOIN blobs b ON b.id = m.blob_id
WHERE m.message_id_hdr = ?1
ORDER BY m.id DESC
LIMIT 1
`

type GetArchivedByMessageIDRow struct {
	ID         int64  `json:"id"`
	CreatedAt  string `json:"created_at"`
	BlobSha256 string `json:"blob_sha256"`
}

// Archived-lookup (API read side): resolve a message by its RFC5322
// Message-ID header across all accounts/folders. Returns the katchup row id,
// when it was archived (created_at), and the blob's content hash. Newest match
// wins when the same Message-ID exists in multiple folders/accounts.
func (q *Queries) GetArchivedByMessageID(ctx context.Context, messageIDHdr sql.NullString) (GetArchivedByMessageIDRow, error) {
	row := q.db.QueryRowContext(ctx, getArchivedByMessageID, messageIDHdr)
	var i GetArchivedByMessageIDRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.BlobSha256)
	return i, err
}

const getBlobBySha = `-- name: GetBlobBySha :one
SELECT id, account_id, sha256, path, size, refcount, created_at
FROM blobs
WHERE account_id = ?1 AND sha256 = ?2
`

type GetBlobByShaParams struct {
	AccountID int64  `json:"account_id"`
	Sha256    string `json:"sha256"`
}

func (q *Queries) GetBlobBySha(ctx context.Context, arg GetBlobByShaParams) (Blob, error) {
	row := q.db.QueryRowContext(ctx, getBlobBySha, arg.AccountID, arg.Sha256)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Sha256,
		&i.Path,
		&i.Size,
		&i.Refcount,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageIDByUID = `-- name: GetMessageIDByUID :one
SELECT id FROM messages
WHERE account_id = ?1 AND folder = ?2 AND uidvalidity = ?3 AND uid = ?4
`

type GetMessageIDByUIDParams struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	Uidvalidity int64  `json:"uidvalidity"`
	Uid         int64  `json:"uid"`
}

// Resolve the messages.id for a (account, folder, uidvalidity, uid) key. Used
// after an idempotent InsertMessage to obtain the row id for search indexing.
func (q *Queries) GetMessageIDByUID(ctx context.Context, arg GetMessageIDByUIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageIDByUID,
		arg.AccountID,
		arg.Folder,
		arg.Uidvalidity,
		arg.Uid,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMessageWithBlob = `-- name: GetMessageWithBlob :one
SELECT
    m.id, m.account_id, m.folder, m.uid, m.blob_id,
    m.message_id_hdr, m.fuzzy_fp, m.from_addr, m.to_addr,
    m.subject, m.internal_date, m.size, m.created_at,
    b.path AS blob_path, b.sha256 AS blob_sha256
FROM messages m
JOIN blobs b ON b.id = m.blob_id
WHERE m.id = ?1
`

type GetMessageWithBlobRow struct {
	ID           int64          `json:"id"`
	AccountID    int64          `json:"account_id"`
	Folder       string         `json:"folder"`
	Uid          int64          `json:"uid"`
	BlobID       int64          `json:"blob_id"`
	MessageIDHdr sql.NullString `json:"message_id_hdr"`
	FuzzyFp      sql.NullString `json:"fuzzy_fp"`
	FromAddr     sql.NullString `json:"from_addr"`
	ToAddr       sql.NullString `json:"to_addr"`
	Subject      sql.NullString `json:"subject"`
	InternalDate sql.NullString `json:"internal_date"`
	Size         int64          `json:"size"`
	CreatedAt    string         `json:"created_at"`
	BlobPath     string         `json:"blob_path"`
	BlobSha256   string         `json:"blob_sha256"`
}

func (q *Queries) GetMessageWithBlob(ctx context.Context, id int64) (GetMessageWithBlobRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageWithBlob, id)
	var i GetMessageWithBlobRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Folder,
		&i.Uid,
		&i.BlobID,
		&i.MessageIDHdr,
		&i.FuzzyFp,
		&i.FromAddr,
		&i.ToAddr,
		&i.Subject,
		&i.InternalDate,
		&i.Size,
		&i.CreatedAt,
		&i.BlobPath,
		&i.BlobSha256,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (
    account_id, folder, uid, blob_id, message_id_hdr, fuzzy_fp,
    from_addr, to_addr, subject, internal_date, size, uidvalidity
)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
ON CONFLICT(account_id, folder, uidvalidity, uid) DO NOTHING
`

type InsertMessageParams struct {
	AccountID    int64          `json:"account_id"`
	Folder       string         `json:"folder"`
	Uid          int64          `json:"uid"`
	BlobID       int64          `json:"blob_id"`
	MessageIDHdr sql.NullString `json:"message_id_hdr"`
	FuzzyFp      sql.NullString `json:"fuzzy_fp"`
	FromAddr     sql.NullString `json:"from_addr"`
	ToAddr       sql.NullString `json:"to_addr"`
	Subject      sql.NullString `json:"subject"`
	InternalDate sql.NullString `json:"internal_date"`
	Size         int64          `json:"size"`
	Uidvalidity  int64          `json:"uidvalidity"`
}

// Idempotent per (account, folder, uidvalidity, uid): re-processing the same
// message (e.g. an aborted batch retried next run) does not create a duplicate row.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.AccountID,
		arg.Folder,
		arg.Uid,
		arg.BlobID,
		arg.MessageIDHdr,
		arg.FuzzyFp,
		arg.FromAddr,
		arg.ToAddr,
		arg.Subject,
		arg.InternalDate,
		arg.Size,
		arg.Uidvalidity,
	)
	return err
}

const listIndexedUIDs = `-- name: ListIndexedUIDs :many
SELECT uid FROM messages
WHERE account_id = ?1 AND folder = ?2 AND uidvalidity = ?3 AND uid > ?4
`

type ListIndexedUIDsParams struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	Uidvalidity int64  `json:"uidvalidity"`
	Uid         int64  `json:"uid"`
}

// UIDs already archived in a folder generation above a watermark, so the sync
// can skip them before downloading any body.
func (q *Queries) ListIndexedUIDs(ctx context.Context, arg ListIndexedUIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listIndexedUIDs,
		arg.AccountID,
		arg.Folder,
		arg.Uidvalidity,
		arg.Uid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var uid int64
		if err := rows.Scan(&uid); err != nil {
			return nil, err
		}
		items = append(items, uid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT
    m.id, m.account_id, m.folder, m.uid, m.blob_id,
    m.message_id_hdr, m.fuzzy_fp, m.from_addr, m.to_addr,
    m.subject, m.internal_date, m.size, m.created_at,
    b.path AS blob_path, b.sha256 AS blob_sha256
FROM messages m
JOIN blobs b ON b.id = m.blob_id
WHERE (?1 = 0 OR m.account_id = ?1)
  AND (?2 = '' OR substr(m.internal_date, 1, 10) = ?2)
  AND (?3 = '' OR m.internal_date >= ?3)
  AND (?4 = '' OR (m.internal_date <> '' AND m.internal_date < ?4))
ORDER BY m.internal_date DESC, m.id DESC
LIMIT ?6 OFFSET ?5
`

type ListMessagesParams struct {
	AccountID interface{} `json:"account_id"`
	Date      interface{} `json:"date"`
	Since     interface{} `json:"since"`
	Before    interface{} `json:"before"`
	RowOffset int64       `json:"row_offset"`
	RowLimit  int64       `json:"row_limit"`
}

type ListMessagesRow struct {
	ID           int64          `json:"id"`
	AccountID    int64          `json:"account_id"`
	Folder       string         `json:"folder"`
	Uid          int64          `json:"uid"`
	BlobID       int64          `json:"blob_id"`
	MessageIDHdr sql.NullString `json:"message_id_hdr"`
	FuzzyFp      sql.NullString `json:"fuzzy_fp"`
	FromAddr     sql.NullString `json:"from_addr"`
	ToAddr       sql.NullString `json:"to_addr"`
	Subject      sql.NullString `json:"subject"`
	InternalDate sql.NullString `json:"internal_date"`
	Size         int64          `json:"size"`
	CreatedAt    string         `json:"created_at"`
	BlobPath     string         `json:"blob_path"`
	BlobSha256   string         `json:"blob_sha256"`
}

// internal_date is RFC3339 UTC, so @since (inclusive) / @before (exclusive) are
// plain string comparisons; pass 'YYYY-MM-DD' or a full timestamp, ” = unbounded.
// Rows with an unknown (”) date never match a bound.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages,
		arg.AccountID,
		arg.Date,
		arg.Since,
		arg.Before,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Folder,
			&i.Uid,
			&i.BlobID,
			&i.MessageIDHdr,
			&i.FuzzyFp,
			&i.FromAddr,
			&i.ToAddr,
			&i.Subject,
			&i.InternalDate,
			&i.Size,
			&i.CreatedAt,
			&i.BlobPath,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessagesLike = `-- name: SearchMessagesLike :many
SELECT
    m.id, m.account_id, m.folder, m.from_addr, m.to_addr,
    m.subject, m.internal_date, m.message_id_hdr
FROM messages m
WHERE (?1 = 0 OR m.account_id = ?1)
  AND (m.subject LIKE ?2 OR m.from_addr LIKE ?2)
  AND (?3 = '' OR m.internal_date >= ?3)
  AND (?4 = '' OR (m.internal_date <> '' AND m.internal_date < ?4))
ORDER BY m.internal_date DESC, m.id DESC
LIMIT ?6 OFFSET ?5
`

type SearchMessagesLikeParams struct {
	AccountID interface{}    `json:"account_id"`
	Q         sql.NullString `json:"q"`
	Since     interface{}    `json:"since"`
	Before    interface{}    `json:"before"`
	RowOffset int64          `json:"row_offset"`
	RowLimit  int64          `json:"row_limit"`
}

type SearchMessagesLikeRow struct {
	ID           int64          `json:"id"`
	AccountID    int64          `json:"account_id"`
	Folder       string         `json:"folder"`
	FromAddr     sql.NullString `json:"from_addr"`
	ToAddr       sql.NullString `json:"to_addr"`
	Subject      sql.NullString `json:"subject"`
	InternalDate sql.NullString `json:"internal_date"`
	MessageIDHdr sql.NullString `json:"message_id_hdr"`
}

// SQLite LIKE fallback for header-only search when Meilisearch is unconfigured.
// Matches subject/from only (headers), never the encrypted body. @q must already
// be wrapped in % wildcards by the caller. @since/@before bound internal_date
// as in ListMessages.
func (q *Queries) SearchMessagesLike(ctx context.Context, arg SearchMessagesLikeParams) ([]SearchMessagesLikeRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMessagesLike,
		arg.AccountID,
		arg.Q,
		arg.Since,
		arg.Before,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesLikeRow{}
	for rows.Next() {
		var i SearchMessagesLikeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Folder,
			&i.FromAddr,
			&i.ToAddr,
			&i.Subject,
			&i.InternalDate,
			&i.MessageIDHdr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlob = `-- name: UpsertBlob :one
INSERT INTO blobs (account_id, sha256, path, size)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(account_id, sha256) DO UPDATE SET refcount = refcount + 1
RETURNING id
`

type UpsertBlobParams struct {
	AccountID int64  `json:"account_id"`
	Sha256    string `json:"sha256"`
	Path      string `json:"path"`
	Size      int64  `json:"size"`
}

// Insert a new blob for (account_id, sha256), or bump the refcount of the
// existing one. Returns the blob id in both cases. path/size are only used on
// the initial insert; a conflict keeps the original file's path and size.
func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertBlob,
		arg.AccountID,
		arg.Sha256,
		arg.Path,
		arg.Size,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
