// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Account struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	Host              string `json:"host"`
	Port              int64  `json:"port"`
	Username          string `json:"username"`
	EncryptedPassword string `json:"encrypted_password"`
	UseSsl            int64  `json:"use_ssl"`
	Folders           string `json:"folders"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type AccountEncryption struct {
	ID                        int64          `json:"id"`
	AccountID                 int64          `json:"account_id"`
	YubikeySlotID             string         `json:"yubikey_slot_id"`
	SlotFingerprint           string         `json:"slot_fingerprint"`
	EncryptedContentKeyPrefix sql.NullString `json:"encrypted_content_key_prefix"`
	CreatedAt                 string         `json:"created_at"`
}

type SyncRun struct {
	ID             int64          `json:"id"`
	AccountID      int64          `json:"account_id"`
	StartedAt      string         `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	EmailsBackedUp int64          `json:"emails_backed_up"`
	Errors         sql.NullString `json:"errors"`
	Status         string         `json:"status"`
	LastUid        sql.NullInt64  `json:"last_uid"`
	CreatedAt      string         `json:"created_at"`
}
