// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Account struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	Host              string `json:"host"`
	Port              int64  `json:"port"`
	Username          string `json:"username"`
	EncryptedPassword string `json:"encrypted_password"`
	UseSsl            int64  `json:"use_ssl"`
	Folders           string `json:"folders"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type AccountEncryption struct {
	ID                        int64          `json:"id"`
	AccountID                 int64          `json:"account_id"`
	YubikeySlotID             string         `json:"yubikey_slot_id"`
	SlotFingerprint           string         `json:"slot_fingerprint"`
	EncryptedContentKeyPrefix sql.NullString `json:"encrypted_content_key_prefix"`
	CreatedAt                 string         `json:"created_at"`
}

type AppSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type Blob struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"account_id"`
	Sha256    string `json:"sha256"`
	Path      string `json:"path"`
	Size      int64  `json:"size"`
	Refcount  int64  `json:"refcount"`
	CreatedAt string `json:"created_at"`
}

type FailedUid struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	Uidvalidity int64  `json:"uidvalidity"`
	Uid         int64  `json:"uid"`
	Attempts    int64  `json:"attempts"`
	LastError   string `json:"last_error"`
	UpdatedAt   string `json:"updated_at"`
}

type FolderSyncState struct {
	AccountID   int64  `json:"account_id"`
	Folder      string `json:"folder"`
	LastUid     int64  `json:"last_uid"`
	UpdatedAt   string `json:"updated_at"`
	Uidvalidity int64  `json:"uidvalidity"`
}

type Message struct {
	ID           int64          `json:"id"`
	AccountID    int64          `json:"account_id"`
	Folder       string         `json:"folder"`
	Uidvalidity  int64          `json:"uidvalidity"`
	Uid          int64          `json:"uid"`
	BlobID       int64          `json:"blob_id"`
	MessageIDHdr sql.NullString `json:"message_id_hdr"`
	FuzzyFp      sql.NullString `json:"fuzzy_fp"`
	FromAddr     sql.NullString `json:"from_addr"`
	ToAddr       sql.NullString `json:"to_addr"`
	Subject      sql.NullString `json:"subject"`
	InternalDate sql.NullString `json:"internal_date"`
	Size         int64          `json:"size"`
	CreatedAt    string         `json:"created_at"`
}

type SyncRun struct {
	ID             int64          `json:"id"`
	AccountID      int64          `json:"account_id"`
	StartedAt      string         `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	EmailsBackedUp int64          `json:"emails_backed_up"`
	Errors         sql.NullString `json:"errors"`
	Status         string         `json:"status"`
	LastUid        sql.NullInt64  `json:"last_uid"`
	CreatedAt      string         `json:"created_at"`
}
