// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_run.sql

package database

import (
	"context"
	"database/sql"
)

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_runs (account_id, started_at, status)
VALUES (?1, datetime('now'), 'running')
RETURNING id, account_id, started_at, finished_at, emails_backed_up, errors, status, last_uid, created_at
`

func (q *Queries) CreateSyncRun(ctx context.Context, accountID int64) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, createSyncRun, accountID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.EmailsBackedUp,
		&i.Errors,
		&i.Status,
		&i.LastUid,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentRuns = `-- name: ListRecentRuns :many
SELECT id, account_id, started_at, finished_at, emails_backed_up, errors, status, last_uid, created_at
FROM sync_runs
WHERE account_id = ?1
ORDER BY started_at DESC, id DESC
LIMIT 20
`

func (q *Queries) ListRecentRuns(ctx context.Context, accountID int64) ([]SyncRun, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRuns, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncRun{}
	for rows.Next() {
		var i SyncRun
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.EmailsBackedUp,
			&i.Errors,
			&i.Status,
			&i.LastUid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSyncRunProgress = `-- name: MarkSyncRunProgress :exec
UPDATE sync_runs SET
    emails_backed_up = ?1,
    last_uid = ?2
WHERE id = ?3
`

type MarkSyncRunProgressParams struct {
	EmailsBackedUp int64         `json:"emails_backed_up"`
	LastUid        sql.NullInt64 `json:"last_uid"`
	ID             int64         `json:"id"`
}

func (q *Queries) MarkSyncRunProgress(ctx context.Context, arg MarkSyncRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, markSyncRunProgress, arg.EmailsBackedUp, arg.LastUid, arg.ID)
	return err
}

const updateSyncRunStatus = `-- name: UpdateSyncRunStatus :one
UPDATE sync_runs SET
    finished_at = datetime('now'),
    emails_backed_up = ?1,
    errors = ?2,
    status = ?3,
    last_uid = ?4
WHERE id = ?5
RETURNING id, account_id, started_at, finished_at, emails_backed_up, errors, status, last_uid, created_at
`

type UpdateSyncRunStatusParams struct {
	EmailsBackedUp int64          `json:"emails_backed_up"`
	Errors         sql.NullString `json:"errors"`
	Status         string         `json:"status"`
	LastUid        sql.NullInt64  `json:"last_uid"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateSyncRunStatus(ctx context.Context, arg UpdateSyncRunStatusParams) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, updateSyncRunStatus,
		arg.EmailsBackedUp,
		arg.Errors,
		arg.Status,
		arg.LastUid,
		arg.ID,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.EmailsBackedUp,
		&i.Errors,
		&i.Status,
		&i.LastUid,
		&i.CreatedAt,
	)
	return i, err
}
