// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"io"
)

type PageData struct {
	Title   string
	Nav     []NavItem
	Active  string
	Content templ.Component
}

type NavItem struct {
	Label  string
	Href   string
	Active bool
}

func Base(data PageData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, _ = w.Write([]byte("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>"))
		_, _ = w.Write([]byte(data.Title))
		_, _ = w.Write([]byte("</title>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n</head>\n<body class=\"bg-gray-100\">\n    <div class=\"flex h-screen\">\n        <aside class=\"w-56 bg-white shadow\">\n            <div class=\"p-4\">\n                <h1 class=\"text-xl font-bold\">Katchup</h1>\n            </div>\n            <nav class=\"mt-4\">\n"))

		for _, item := range data.Nav {
			active := ""
			if item.Active {
				active = " bg-gray-100 text-gray-900"
			} else {
				active = " text-gray-600 hover:bg-gray-50"
			}
			_, _ = w.Write([]byte("                <a href=\""))
			_, _ = w.Write([]byte(item.Href))
			_, _ = w.Write([]byte("\" class=\""))
			_, _ = w.Write([]byte(active))
			_, _ = w.Write([]byte(" block px-4 py-2\">\n                    "))
			_, _ = w.Write([]byte(item.Label))
			_, _ = w.Write([]byte("\n                </a>\n"))
		}

		_, _ = w.Write([]byte("            </nav>\n        </aside>\n        <main class=\"flex-1 overflow-auto\">\n"))

		err := data.Content.Render(ctx, w)
		if err != nil {
			return err
		}

		_, _ = w.Write([]byte("        </main>\n    </div>\n</body>\n</html>"))
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
