// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package account

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"fmt"
	"io"
)

type PageData struct {
	Title    string
	Accounts []AccountView
	Account  *AccountView
	Errors   []string
}

type AccountView struct {
	ID        int64
	Name      string
	Host      string
	Port      int64
	Username  string
	UseSsl    bool
	Folders   string
	CreatedAt string
	UpdatedAt string
	IsSyncing bool
}

func ListPage(data PageData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := fmt.Fprintf(w, `<nav class="bg-white shadow">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="flex justify-between h-16">
			<div class="flex">
				<div class="shrink-0 flex items-center">
					<span class="text-xl font-bold text-gray-800">Katchup</span>
				</div>
				<div class="ml-6 flex space-x-4 self-center">
					<a href="/accounts" class="text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 border-indigo-500 text-sm font-medium">Accounts</a>
					<a href="/sync" class="text-gray-500 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium">Sync</a>
					<a href="/browse" class="text-gray-500 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium">Browse</a>
				</div>
			</div>
			<div class="flex items-center">
				<a href="/accounts/new" class="bg-indigo-600 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-indigo-700">Add Account</a>
			</div>
		</div>
	</div>
</nav>
<main class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
	<div class="px-4 py-6 sm:px-0">
`)

		if len(data.Accounts) == 0 {
			_, err := fmt.Fprintf(w, `		<div class="text-center py-12">
			<h3 class="mt-2 text-sm font-medium text-gray-900">No accounts yet</h3>
			<p class="mt-1 text-sm text-gray-500">Get started by creating a new email account.</p>
			<div class="mt-6">
				<a href="/accounts/new" class="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">Add Account</a>
			</div>
		</div>`)
			return err
		}

		_, err = fmt.Fprintf(w, `		<div class="flex justify-between items-center mb-4">
			<h2 class="text-lg leading-6 font-medium text-gray-900">Email Accounts (%d)</h2>
		</div>
		<div class="bg-white shadow overflow-hidden sm:rounded-lg">
			<table class="min-w-full divide-y divide-gray-200">
				<thead class="bg-gray-50">
					<tr>
						<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
						<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Host</th>
						<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Username</th>
						<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Folders</th>
						<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
						<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
					</tr>
				</thead>
				<tbody class="bg-white divide-y divide-gray-200">
`, len(data.Accounts))
		if err != nil {
			return err
		}

		for _, acct := range data.Accounts {
			_, err = fmt.Fprintf(w, `					<tr>
						<td class="px-6 py-4 whitespace-nowrap">
							<div class="text-sm font-medium text-gray-900">%s</div>
						</td>
						<td class="px-6 py-4 whitespace-nowrap">
							<div class="text-sm text-gray-500">%s:%d</div>
						</td>
						<td class="px-6 py-4 whitespace-nowrap">
							<div class="text-sm text-gray-500">%s</div>
						</td>
						<td class="px-6 py-4 whitespace-nowrap">
							<div class="text-sm text-gray-500">%s</div>
						</td>
						<td class="px-6 py-4 whitespace-nowrap">
							<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium">
								<span class="w-2 h-2 mr-1 rounded-full %s"></span>
								%s
							</span>
						</td>
						<td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
							<a href="/accounts/%d/edit" class="text-indigo-600 hover:text-indigo-900 mr-3">Edit</a>
							<form method="POST" action="/accounts/%d/delete" onsubmit="return confirm('Are you sure? This will delete the account and all synced emails.')" class="inline">
								<button type="submit" class="text-red-600 hover:text-red-900">Delete</button>
							</form>
						</td>
					</tr>
`, acct.Name, acct.Host, acct.Port, acct.Username, acct.Folders, "bg-gray-400", "Never", acct.ID, acct.ID)
			if err != nil {
				return err
			}
		}

		_, err = fmt.Fprintf(w, `				</tbody>
			</table>
		</div>
	</div>
</main>`)
		return err
	})
}

func FormPage(data PageData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		isEdit := data.Account != nil
		pageTitle := "Add Account"
		action := "/accounts/new"
		buttonLabel := "Save"

		if isEdit {
			pageTitle = "Edit Account"
			action = fmt.Sprintf("/accounts/%d/edit", data.Account.ID)
			buttonLabel = "Update"
		}

		_, err := fmt.Fprintf(w, `<nav class="bg-white shadow">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="flex justify-between h-16">
			<div class="flex">
				<div class="shrink-0 flex items-center">
					<span class="text-xl font-bold text-gray-800">Katchup</span>
				</div>
				<div class="ml-6 flex space-x-4 self-center">
					<a href="/accounts" class="text-gray-500 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium">Accounts</a>
					<a href="/sync" class="text-gray-500 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium">Sync</a>
					<a href="/browse" class="text-gray-500 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium">Browse</a>
				</div>
			</div>
		</div>
	</div>
</nav>
<main class="max-w-3xl mx-auto py-6 sm:px-6 lg:px-8">
	<div class="px-4 py-6 sm:px-0">
		<h2 class="text-lg leading-6 font-medium text-gray-900 mb-6">%s</h2>
`, pageTitle)
		if err != nil {
			return err
		}

		// Render errors
		if len(data.Errors) > 0 {
			_, err = fmt.Fprint(w, `		<div class="bg-red-50 border border-red-200 rounded-md p-4 mb-6">
			<ul class="list-disc list-inside text-sm text-red-700">
`)
			if err != nil {
				return err
			}
			for _, e := range data.Errors {
				_, err = fmt.Fprintf(w, `				<li>%s</li>
`, e)
				if err != nil {
					return err
				}
			}
			_, err = fmt.Fprint(w, `			</ul>
		</div>
`)
			if err != nil {
				return err
			}
		}

		// Fill form values
		name := ""
		host := ""
		port := "993"
		username := ""
		useSsl := "1"
		folders := "INBOX"

		if data.Account != nil {
			name = data.Account.Name
			host = data.Account.Host
			port = fmt.Sprintf("%d", data.Account.Port)
			username = data.Account.Username
			if data.Account.UseSsl {
				useSsl = "1"
			} else {
				useSsl = "0"
			}
			folders = data.Account.Folders
		}

		sslChecked1 := ""
		sslChecked0 := ""
		if useSsl == "1" {
			sslChecked1 = " checked"
		} else {
			sslChecked0 = " checked"
		}

		_, err = fmt.Fprintf(w, `		<form method="POST" action="%s" class="space-y-6 bg-white shadow sm:rounded-lg">
			<div class="px-4 py-5 sm:p-6 space-y-4">
				<div>
					<label for="name" class="block text-sm font-medium text-gray-700">Name</label>
					<input type="text" name="name" id="name" value="%s" required class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
				</div>
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label for="host" class="block text-sm font-medium text-gray-700">Host</label>
						<input type="text" name="host" id="host" value="%s" required placeholder="imap.gmail.com" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
					</div>
					<div>
						<label for="port" class="block text-sm font-medium text-gray-700">Port</label>
						<input type="number" name="port" id="port" value="%s" required class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
					</div>
				</div>
				<div>
					<label for="username" class="block text-sm font-medium text-gray-700">Username</label>
					<input type="text" name="username" id="username" value="%s" required placeholder="you@example.com" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
				</div>
				<div>
					<label for="password" class="block text-sm font-medium text-gray-700">Password</label>
					<input type="password" name="password" id="password" required placeholder="Account password or app-specific password" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
					<p class="mt-1 text-xs text-gray-500">Encrypted at rest with your master key.</p>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Connection</label>
					<div class="flex space-x-6">
						<label class="inline-flex items-center">
							<input type="radio" name="connection" value="993" id="conn-993"%s class="form-radio text-indigo-600">
							<span class="ml-2 text-sm text-gray-700">IMAPS (port 993)</span>
						</label>
						<label class="inline-flex items-center">
							<input type="radio" name="connection" value="143" id="conn-143"%s class="form-radio text-indigo-600">
							<span class="ml-2 text-sm text-gray-700">STARTTLS (port 143)</span>
						</label>
					</div>
				</div>
				<div>
					<label for="folders" class="block text-sm font-medium text-gray-700">Folders</label>
					<input type="text" name="folders" id="folders" value="%s" placeholder="INBOX, Sent, Archive" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
					<p class="mt-1 text-xs text-gray-500">Comma-separated folder names (default: INBOX)</p>
				</div>
				<div>
					<label for="slot" class="block text-sm font-medium text-gray-700">YubiKey Slot</label>
					<select name="slot" id="slot" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
						<option value="9a" selected>9a (primary)</option>
						<option value="9b">9b</option>
						<option value="9c">9c</option>
						<option value="9d">9d</option>
					</select>
				</div>
			</div>
			<div class="px-4 py-3 bg-gray-50 text-right sm:px-6 sm:rounded-b-lg flex justify-end space-x-3">
				<a href="/accounts" class="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">Cancel</a>
				<button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">%s</button>
			</div>
		</form>
`, action, name, host, port, username, sslChecked1, sslChecked0, folders, buttonLabel)
		if err != nil {
			return err
		}

		_, err = fmt.Fprintf(w, `	</div>
</main>`)
		return err
	})
}

var _ = templruntime.GeneratedTemplate
