// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package account

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"context"
	"fmt"
	"html"
	"io"
	"strings"

	"katchup/internal/view/layout"

	"github.com/a-h/templ"
)

type PageData struct {
	Title    string
	Accounts []AccountView
	Account  *AccountView
	Errors   []string
}

type AccountView struct {
	ID        int64
	Name      string
	Host      string
	Port      int64
	Username  string
	UseSsl    bool
	Folders   string
	CreatedAt string
	UpdatedAt string
	IsSyncing bool
}

func ListPage(data PageData) templ.Component {
	inner := templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		var b strings.Builder

		action := `<a href="/accounts/new" class="inline-flex items-center gap-2 rounded-xl bg-ketchup px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-ketchup/25 transition hover:bg-ketchup-600 hover:shadow-ketchup/40">
			<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></svg>
			Add account</a>`
		b.WriteString(`<div class="rise">`)
		b.WriteString(layout.PageHeader("Mailboxes", "Accounts", "IMAP mailboxes katchup connects to and archives on a schedule.", action))

		if len(data.Accounts) == 0 {
			b.WriteString(`<div class="rounded-2xl border border-dashed border-white/12 bg-ink-900/40 px-6 py-20 text-center">
				<div class="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-ketchup/10 text-2xl ring-1 ring-inset ring-ketchup/25">📬</div>
				<h3 class="font-display text-lg font-semibold text-white">No mailboxes yet</h3>
				<p class="mx-auto mt-1 max-w-sm text-sm text-mute">Connect an IMAP account and katchup will begin backing up every message, encrypted at rest.</p>
				<a href="/accounts/new" class="mt-6 inline-flex items-center gap-2 rounded-xl bg-ketchup px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-ketchup/25 transition hover:bg-ketchup-600">Add your first account</a>
			</div></div>`)
			_, err := io.WriteString(w, b.String())
			return err
		}

		b.WriteString(`<div class="overflow-hidden rounded-2xl border border-white/10 bg-ink-900/60 shadow-2xl shadow-black/40">
			<div class="overflow-x-auto">
			<table class="w-full min-w-[720px] text-sm">
				<thead>
					<tr class="border-b border-white/10 text-left font-mono text-[11px] uppercase tracking-widest text-mute">
						<th class="px-5 py-3.5 font-medium">Name</th>
						<th class="px-5 py-3.5 font-medium">Host</th>
						<th class="px-5 py-3.5 font-medium">Username</th>
						<th class="px-5 py-3.5 font-medium">Folders</th>
						<th class="px-5 py-3.5 font-medium">Status</th>
						<th class="px-5 py-3.5 text-right font-medium">Actions</th>
					</tr>
				</thead>
				<tbody class="divide-y divide-white/5">`)

		for _, acct := range data.Accounts {
			dot, label, tone := "bg-zinc-500", "Never synced", "text-mute"
			live := ""
			if acct.IsSyncing {
				dot, label, tone, live = "bg-emerald-400", "Syncing", "text-emerald-300", " live-dot"
			} else if acct.UpdatedAt != "" {
				dot, label, tone = "bg-emerald-500/80", "Synced", "text-zinc-300"
			}

			folders := ""
			for _, f := range strings.Split(acct.Folders, ",") {
				f = strings.TrimSpace(f)
				if f == "" {
					continue
				}
				folders += `<span class="rounded-md bg-white/5 px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">` + html.EscapeString(f) + `</span> `
			}

			fmt.Fprintf(&b, `<tr class="group transition-colors hover:bg-white/[0.025]">
				<td class="px-5 py-4"><div class="font-medium text-white">%s</div></td>
				<td class="px-5 py-4"><span class="font-mono text-[13px] text-zinc-400">%s:%d</span></td>
				<td class="px-5 py-4 text-zinc-400">%s</td>
				<td class="px-5 py-4">%s</td>
				<td class="px-5 py-4">
					<span class="inline-flex items-center gap-2 rounded-full bg-white/5 px-2.5 py-1 text-xs font-medium %s">
						<span class="h-1.5 w-1.5 rounded-full %s%s"></span>%s
					</span>
				</td>
				<td class="px-5 py-4">
					<div class="flex items-center justify-end gap-1.5">
						<a href="/accounts/%d/edit" class="rounded-lg border border-white/10 px-3 py-1.5 text-xs font-medium text-zinc-300 transition hover:border-white/20 hover:bg-white/5 hover:text-white">Edit</a>
						<form method="POST" action="/accounts/%d/delete" onsubmit="return confirm('Delete this account and every synced email? This cannot be undone.')">
							<button type="submit" class="rounded-lg border border-transparent px-3 py-1.5 text-xs font-medium text-red-400/80 transition hover:border-red-500/30 hover:bg-red-500/10 hover:text-red-300">Delete</button>
						</form>
					</div>
				</td>
			</tr>`, html.EscapeString(acct.Name), html.EscapeString(acct.Host), acct.Port, html.EscapeString(acct.Username), folders, tone, dot, live, label, acct.ID, acct.ID)
		}

		b.WriteString(`</tbody></table></div></div></div>`)
		_, err := io.WriteString(w, b.String())
		return err
	})
	return layout.Document("Accounts", "accounts", inner)
}

func FormPage(data PageData) templ.Component {
	inner := templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		isEdit := data.Account != nil
		title, eyebrow, action, buttonLabel := "Add account", "New mailbox", "/accounts/new", "Save account"
		if isEdit {
			title, eyebrow = "Edit account", "Mailbox"
			action = fmt.Sprintf("/accounts/%d/edit", data.Account.ID)
			buttonLabel = "Save changes"
		}

		name, host, port, username, folders := "", "", "993", "", "INBOX"
		ssl := true
		if data.Account != nil {
			a := data.Account
			name, host, username, folders = a.Name, a.Host, a.Username, a.Folders
			port = fmt.Sprintf("%d", a.Port)
			ssl = a.UseSsl
		}
		sslChecked, starttlsChecked := "", ""
		if ssl {
			sslChecked = " checked"
		} else {
			starttlsChecked = " checked"
		}
		passPlaceholder := "App password or account password"
		passRequired := " required"
		if isEdit {
			passPlaceholder = "Leave blank to keep the current password"
			passRequired = ""
		}

		var b strings.Builder
		b.WriteString(`<div class="rise mx-auto max-w-2xl">`)
		b.WriteString(layout.PageHeader(eyebrow, title, "Credentials are encrypted at rest with your master key.", ""))

		if len(data.Errors) > 0 {
			b.WriteString(`<div class="mb-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4">
				<p class="mb-2 flex items-center gap-2 text-sm font-semibold text-red-300"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 9v4m0 4h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"/></svg>Please fix the following</p>
				<ul class="list-inside list-disc space-y-1 pl-1 text-sm text-red-200/90">`)
			for _, e := range data.Errors {
				b.WriteString(`<li>` + html.EscapeString(e) + `</li>`)
			}
			b.WriteString(`</ul></div>`)
		}

		label := func(f, t string) string {
			return fmt.Sprintf(`<label for="%s" class="mb-1.5 block text-xs font-medium uppercase tracking-wide text-mute">%s</label>`, f, t)
		}
		inputCls := "w-full rounded-xl border border-white/10 bg-ink-950/60 px-3.5 py-2.5 text-sm text-white placeholder:text-zinc-600 outline-none transition focus:border-ketchup/60 focus:ring-2 focus:ring-ketchup/25"

		fmt.Fprintf(&b, `<form method="POST" action="%s" class="space-y-5 rounded-2xl border border-white/10 bg-ink-900/60 p-6 shadow-2xl shadow-black/40 sm:p-7">
			<div>%s<input type="text" name="name" id="name" value="%s" required placeholder="Personal Gmail" class="%s"></div>
			<div class="grid grid-cols-1 gap-5 sm:grid-cols-[2fr,1fr]">
				<div>%s<input type="text" name="host" id="host" value="%s" required placeholder="imap.gmail.com" class="%s font-mono"></div>
				<div>%s<input type="number" name="port" id="port" value="%s" required class="%s font-mono"></div>
			</div>
			<div>%s<input type="text" name="username" id="username" value="%s" required placeholder="you@example.com" class="%s font-mono"></div>
			<div>%s<input type="password" name="password" id="password"%s placeholder="%s" class="%s font-mono"><p class="mt-1.5 flex items-center gap-1.5 text-xs text-mute"><svg class="h-3.5 w-3.5 text-ketchup/70" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 15v2m-6 4h12a2 2 0 0 0 2-2v-6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2Zm10-10V7a4 4 0 0 0-8 0v4"/></svg>Encrypted at rest with your master key.</p></div>
			<div>
				<span class="mb-1.5 block text-xs font-medium uppercase tracking-wide text-mute">Connection</span>
				<div class="grid grid-cols-2 gap-3">
					<label class="flex cursor-pointer items-center gap-2.5 rounded-xl border border-white/10 bg-ink-950/40 px-3.5 py-3 text-sm transition has-[:checked]:border-ketchup/60 has-[:checked]:bg-ketchup/10">
						<input type="radio" name="connection" value="993"%s class="accent-ketchup"><span class="text-zinc-200">IMAPS<span class="ml-1 font-mono text-xs text-mute">:993</span></span>
					</label>
					<label class="flex cursor-pointer items-center gap-2.5 rounded-xl border border-white/10 bg-ink-950/40 px-3.5 py-3 text-sm transition has-[:checked]:border-ketchup/60 has-[:checked]:bg-ketchup/10">
						<input type="radio" name="connection" value="143"%s class="accent-ketchup"><span class="text-zinc-200">STARTTLS<span class="ml-1 font-mono text-xs text-mute">:143</span></span>
					</label>
				</div>
			</div>
			<div>%s<input type="text" name="folders" id="folders" value="%s" placeholder="INBOX, Sent, Archive" class="%s"><p class="mt-1.5 text-xs text-mute">Comma-separated folder names. Defaults to INBOX.</p></div>
			<div>%s<select name="slot" id="slot" class="%s"><option value="9a">9a (primary)</option><option value="9b">9b</option><option value="9c">9c</option><option value="9d">9d</option></select></div>
			<div class="flex items-center justify-end gap-3 border-t border-white/10 pt-5">
				<a href="/accounts" class="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium text-zinc-300 transition hover:bg-white/5">Cancel</a>
				<button type="submit" class="inline-flex items-center gap-2 rounded-xl bg-ketchup px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-ketchup/25 transition hover:bg-ketchup-600 hover:shadow-ketchup/40">%s</button>
			</div>
		</form></div>`,
			action,
			label("name", "Display name"), html.EscapeString(name), inputCls,
			label("host", "IMAP host"), html.EscapeString(host), inputCls,
			label("port", "Port"), html.EscapeString(port), inputCls,
			label("username", "Username"), html.EscapeString(username), inputCls,
			label("password", "Password"), passRequired, passPlaceholder, inputCls,
			sslChecked, starttlsChecked,
			label("folders", "Folders"), html.EscapeString(folders), inputCls,
			label("slot", "YubiKey slot"), inputCls,
			buttonLabel)

		_, err := io.WriteString(w, b.String())
		return err
	})
	return layout.Document(data.Title, "accounts", inner)
}
