// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package sync

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"fmt"
	"io"
)

type PageData struct {
	Title    string
	Accounts []AccountSyncView
}

type AccountSyncView struct {
	ID             int64
	Name           string
	Host           string
	Username       string
	Folders        string
	IsSyncing      bool
	LastSyncAt     string
	LastUID        string
	EmailsBackedUp int64
	Errors         string
	RecentRuns     []SyncRunView
}

type SyncRunView struct {
	ID             int64
	StartedAt      string
	FinishedAt     string
	EmailsBackedUp int64
	Errors         string
	Status         string
	LastUID        string
}

func StatusPage(data PageData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := fmt.Fprintf(w, `<nav class="bg-white shadow">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="flex justify-between h-16">
			<div class="flex">
				<div class="shrink-0 flex items-center">
					<span class="text-xl font-bold text-gray-800">Katchup</span>
				</div>
				<div class="ml-6 flex space-x-4 self-center">
					<a href="/accounts" class="text-gray-500 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium">Accounts</a>
					<a href="/sync" class="text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 border-indigo-500 text-sm font-medium">Sync</a>
					<a href="/browse" class="text-gray-500 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium">Browse</a>
				</div>
			</div>
			<div class="flex items-center">
				<button id="refresh-btn" onclick="location.reload()" class="text-gray-600 hover:text-gray-900 inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md">
					Refresh
				</button>
			</div>
		</div>
	</div>
</nav>
<main class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
	<div class="px-4 py-6 sm:px-0">
		<h2 class="text-lg leading-6 font-medium text-gray-900 mb-4">Sync Status</h2>
`)
		if err != nil {
			return err
		}

		if len(data.Accounts) == 0 {
			_, err := fmt.Fprint(w, `		<div class="text-center py-12">
			<h3 class="mt-2 text-sm font-medium text-gray-900">No accounts yet</h3>
			<p class="mt-1 text-sm text-gray-500">Add an email account to start syncing.</p>
			<div class="mt-6">
				<a href="/accounts/new" class="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">Add Account</a>
			</div>
		</div>`)
			return err
		}

		for i, acct := range data.Accounts {
			_, err := fmt.Fprintf(w, `		<div class="bg-white shadow overflow-hidden sm:rounded-lg mb-6">
			<div class="px-4 py-5 sm:px-6 flex justify-between items-center">
				<div>
					<h3 class="text-lg leading-6 font-medium text-gray-900">%s</h3>
					<p class="mt-1 text-sm text-gray-500">%s — %s</p>
				</div>
				<div class="flex items-center space-x-3">
`, acct.Name, acct.Host, acct.Username)
			if err != nil {
				return err
			}

			if acct.IsSyncing {
				_, err = fmt.Fprintf(w, `					<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium">
						<span class="w-2 h-2 mr-1 rounded-full bg-green-500 animate-pulse"></span>
						Running
					</span>
`)
			} else if acct.LastSyncAt != "" {
				_, err = fmt.Fprintf(w, `					<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium">
						<span class="w-2 h-2 mr-1 rounded-full bg-gray-400"></span>
						Completed
					</span>
`)
			} else {
				_, err = fmt.Fprintf(w, `					<span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium">
						<span class="w-2 h-2 mr-1 rounded-full bg-gray-400"></span>
						Never synced
					</span>
`)
			}
			if err != nil {
				return err
			}

			_, err = fmt.Fprintf(w, `					<form method="POST" action="/sync/%d/trigger">
						<button type="submit" class="inline-flex items-center px-3 py-1.5 border border-transparent shadow-sm text-xs font-medium rounded text-white bg-indigo-600 hover:bg-indigo-700">Trigger Sync</button>
					</form>
				</div>
			</div>
`, acct.ID)
			if err != nil {
				return err
			}

			// Sync info row
			_, err = fmt.Fprintf(w, `			<div class="border-t border-gray-200 px-4 py-4 sm:px-6 grid grid-cols-3 gap-4 text-sm">
				<div>
					<p class="text-gray-500">Last Sync</p>
					<p class="font-medium text-gray-900">%s</p>
				</div>
				<div>
					<p class="text-gray-500">Emails Backed Up</p>
					<p class="font-medium text-gray-900">%d</p>
				</div>
				<div>
					<p class="text-gray-500">Folders</p>
					<p class="font-medium text-gray-900">%s</p>
				</div>
`, acct.LastSyncAt, acct.EmailsBackedUp, acct.Folders)
			if err != nil {
				return err
			}

			if acct.Errors != "" {
				_, err = fmt.Fprintf(w, `				<div>
					<p class="text-gray-500">Last Error</p>
					<p class="font-medium text-red-600">%s</p>
				</div>
`, acct.Errors)
				if err != nil {
					return err
				}
			}

			_, err = fmt.Fprintf(w, `			</div>
`)
			if err != nil {
				return err
			}

			// Recent runs
			if len(acct.RecentRuns) > 0 {
				_, err = fmt.Fprintf(w, `			<div class="border-t border-gray-200 px-4 py-4 sm:px-6">
				<h4 class="text-sm font-medium text-gray-900 mb-3">Recent Sync Runs</h4>
				<table class="min-w-full divide-y divide-gray-200">
					<thead class="bg-gray-50">
						<tr>
							<th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">Started</th>
							<th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">Finished</th>
							<th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
							<th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">Emails</th>
							<th scope="col" class="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">Errors</th>
						</tr>
					</thead>
					<tbody class="bg-white divide-y divide-gray-200">
`)
				if err != nil {
					return err
				}

				for _, run := range acct.RecentRuns {
					_, err = fmt.Fprintf(w, `						<tr>
							<td class="px-3 py-2 whitespace-nowrap text-sm text-gray-900">%s</td>
							<td class="px-3 py-2 whitespace-nowrap text-sm text-gray-500">%s</td>
							<td class="px-3 py-2 whitespace-nowrap">
								<span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium">
									<span class="w-1.5 h-1.5 mr-1 rounded-full %s"></span>
									%s
								</span>
							</td>
							<td class="px-3 py-2 whitespace-nowrap text-sm text-gray-900">%d</td>
							<td class="px-3 py-2 text-sm text-gray-500 max-w-xs truncate">%s</td>
						</tr>
`, run.StartedAt, run.FinishedAt, run.Status, run.Status, run.EmailsBackedUp, run.Errors)
					if err != nil {
						return err
					}
				}

				_, err = fmt.Fprintf(w, `					</tbody>
				</table>
			</div>
`)
				if err != nil {
					return err
				}
			}

			_, err = fmt.Fprintf(w, `		</div>
`)
			if err != nil {
				return err
			}

			// Add refresh interval for running accounts
			if i == 0 && hasRunningSync(data.Accounts) {
				_, err = fmt.Fprint(w, `	<script>
		setInterval(function() { location.reload(); }, 10000);
	</script>
`)
				if err != nil {
					return err
				}
			}
		}

		_, err = fmt.Fprint(w, `	</div>
</main>`)
		return err
	})
}

func hasRunningSync(accounts []AccountSyncView) bool {
	for _, a := range accounts {
		if a.IsSyncing {
			return true
		}
	}
	return false
}

var _ = templruntime.GeneratedTemplate
