// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package browse

import (
	"context"
	"fmt"
	"html"
	"io"
	"strings"

	"katchup/internal/view/layout"

	"github.com/a-h/templ"
)

type PageData struct {
	Title     string
	Accounts  []AccountView
	Emails    []EmailView
	AccountID int64
	Date      string
	Page      int
	PerPage   int
	Total     int
}

type AccountView struct {
	ID     int64
	Name   string
	Emails int64
}

type EmailView struct {
	Date      string
	Filename  string
	Folder    string
	Size      int64
	AccountID int64
}

func humanBytes(n int64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for x := n / unit; x >= unit; x /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(n)/float64(div), "KMGTPE"[exp])
}

func BrowsePage(data PageData) templ.Component {
	inner := templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		var b strings.Builder
		b.WriteString(`<div class="rise">`)
		b.WriteString(layout.PageHeader("Archive", "Browse", "Search and download individual messages from your encrypted archive.", ""))

		// Filter bar
		inputCls := "rounded-xl border border-white/10 bg-ink-950/60 px-3.5 py-2.5 text-sm text-white outline-none transition focus:border-ketchup/60 focus:ring-2 focus:ring-ketchup/25"
		b.WriteString(`<form method="GET" action="/browse" class="mb-6 flex flex-wrap items-end gap-3 rounded-2xl border border-white/10 bg-ink-900/60 p-4">
			<div class="flex flex-col gap-1.5">
				<label for="account" class="font-mono text-[11px] uppercase tracking-widest text-mute">Account</label>
				<select name="account" id="account" class="` + inputCls + ` min-w-[200px]">
					<option value="">All accounts</option>`)
		for _, acct := range data.Accounts {
			sel := ""
			if acct.ID == data.AccountID {
				sel = " selected"
			}
			fmt.Fprintf(&b, `<option value="%d"%s>%s (%s)</option>`, acct.ID, sel, html.EscapeString(acct.Name), commasInt(acct.Emails))
		}
		fmt.Fprintf(&b, `</select>
			</div>
			<div class="flex flex-col gap-1.5">
				<label for="date" class="font-mono text-[11px] uppercase tracking-widest text-mute">Date</label>
				<input type="date" name="date" id="date" value="%s" class="%s">
			</div>
			<button type="submit" class="inline-flex items-center gap-2 rounded-xl bg-ketchup px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-ketchup/25 transition hover:bg-ketchup-600">
				<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3"/></svg>
				Filter
			</button>
		</form>`, html.EscapeString(data.Date), inputCls)

		if len(data.Emails) == 0 {
			b.WriteString(`<div class="rounded-2xl border border-dashed border-white/12 bg-ink-900/40 px-6 py-20 text-center">
				<div class="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-white/5 text-2xl ring-1 ring-inset ring-white/10">🔍</div>
				<h3 class="font-display text-lg font-semibold text-white">No emails found</h3>
				<p class="mx-auto mt-1 max-w-sm text-sm text-mute">Nothing in the archive matches these filters. Try a different account or date.</p>
			</div></div>`)
			_, err := io.WriteString(w, b.String())
			return err
		}

		b.WriteString(`<div class="overflow-hidden rounded-2xl border border-white/10 bg-ink-900/60 shadow-2xl shadow-black/40">
			<div class="overflow-x-auto">
			<table class="w-full min-w-[640px] text-sm">
				<thead><tr class="border-b border-white/10 text-left font-mono text-[11px] uppercase tracking-widest text-mute">
					<th class="px-5 py-3.5 font-medium">Date</th>
					<th class="px-5 py-3.5 font-medium">Folder</th>
					<th class="px-5 py-3.5 font-medium">Message</th>
					<th class="px-5 py-3.5 font-medium">Size</th>
					<th class="px-5 py-3.5 text-right font-medium">Actions</th>
				</tr></thead>
				<tbody class="divide-y divide-white/5">`)
		for _, e := range data.Emails {
			fmt.Fprintf(&b, `<tr class="group transition-colors hover:bg-white/[0.025]">
				<td class="px-5 py-3.5 font-mono text-xs text-zinc-300">%s</td>
				<td class="px-5 py-3.5"><span class="rounded-md bg-white/5 px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">%s</span></td>
				<td class="px-5 py-3.5 font-mono text-xs text-mute">%s</td>
				<td class="px-5 py-3.5 font-mono text-xs text-zinc-400 tabular-nums">%s</td>
				<td class="px-5 py-3.5 text-right">
					<a href="/browse/%d/%s/%s" class="inline-flex items-center gap-1.5 rounded-lg border border-white/10 px-3 py-1.5 text-xs font-medium text-zinc-300 transition hover:border-ketchup/50 hover:bg-ketchup/10 hover:text-white">
						<svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/></svg>
						Download
					</a>
				</td>
			</tr>`, html.EscapeString(e.Date), html.EscapeString(orDash(e.Folder)), html.EscapeString(e.Filename), humanBytes(e.Size),
				e.AccountID, html.EscapeString(e.Date), html.EscapeString(e.Filename))
		}
		b.WriteString(`</tbody></table></div>`)

		// Pagination
		if data.Total > data.PerPage {
			totalPages := (data.Total + data.PerPage - 1) / data.PerPage
			b.WriteString(`<div class="flex items-center justify-between gap-4 border-t border-white/10 px-5 py-3.5">`)
			fmt.Fprintf(&b, `<p class="font-mono text-xs text-mute">Page <span class="text-zinc-200">%d</span> of <span class="text-zinc-200">%d</span> · <span class="text-zinc-200">%s</span> emails</p>`, data.Page, totalPages, commasInt(int64(data.Total)))
			b.WriteString(`<div class="flex items-center gap-1.5">`)

			pageBtn := func(page int, labelHTML string, enabled, active bool) {
				if active {
					fmt.Fprintf(&b, `<span class="rounded-lg bg-ketchup px-3 py-1.5 text-xs font-semibold text-white">%s</span>`, labelHTML)
					return
				}
				if !enabled {
					fmt.Fprintf(&b, `<span class="rounded-lg border border-white/5 px-3 py-1.5 text-xs font-medium text-zinc-600">%s</span>`, labelHTML)
					return
				}
				fmt.Fprintf(&b, `<a href="/browse?account=%d&date=%s&page=%d" class="rounded-lg border border-white/10 px-3 py-1.5 text-xs font-medium text-zinc-300 transition hover:border-white/25 hover:bg-white/5 hover:text-white">%s</a>`,
					data.AccountID, html.EscapeString(data.Date), page, labelHTML)
			}

			pageBtn(data.Page-1, "Prev", data.Page > 1, false)

			start := data.Page - 2
			if start < 1 {
				start = 1
			}
			end := start + 4
			if end > totalPages {
				end = totalPages
			}
			if end-start < 4 {
				start = end - 4
				if start < 1 {
					start = 1
				}
			}
			for p := start; p <= end; p++ {
				pageBtn(p, fmt.Sprintf("%d", p), true, p == data.Page)
			}

			pageBtn(data.Page+1, "Next", data.Page < totalPages, false)
			b.WriteString(`</div></div>`)
		}

		b.WriteString(`</div></div>`)
		_, err := io.WriteString(w, b.String())
		return err
	})
	return layout.Document("Browse", "browse", inner)
}

func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "—"
	}
	return s
}

func commasInt(n int64) string {
	s := fmt.Sprintf("%d", n)
	var out []byte
	for i, c := range []byte(s) {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, c)
	}
	return string(out)
}
